potential_animals:
  - alligator
  - anglerfish
  - ant
  - anteater
  - badger
  - bass
  - beaver
  - bird
  - blobfish
  - boar
  - budgie
  - black_bear
  - beetle
  - capybara
  - catfish
  - cavefish
  - caterpillar
  - clam
  - crab
  - crow_&_raven
  - coyote
  - deer
  - desert_scorpion
  - dragonfly
  - duck
  - eagle
  - eel
  - elephant
  - fennec_fox
  - firefly
  - flamingo
  - flying_fish
  - fennec_fox
  - giant_isopod
  - giant_salamander
  - giraffe
  - goose
  - gorilla
  - grizzly_bear
  - hamster
  - hedgehog
  - hippo
  - hyena
  - iguana
  - jellyfish_&_small_jellyfish
  - jungle_scorpion
  - kakapo
  - kangaroo
  - kiwi
  - komodo_dragon
  - lion
  - lizard
  - mammoth
  - mole
  - monkey
  - moose
  - octopus
  - orca
  - otter
  - ostrich
  - owl
  - peafowl
  - penguin
  - piranha
  - platypus
  - racoon
  - rat
  - red_panda
  - rhino
  - seals
  - secretary_bird
  - shark
  - skunk
  - sloth
  - slug
  - snail
  - snake
  - squirrel
  - starfish
  - stingray
  - termite
  - tiger
  - tortoise
  - toucan
  - tree_frog
  - turkey
  - vulture
  - walrus
  - whale
  - zebra 