return_link:
  en: Naturalist Add-On Wiki
  fr: Wiki de l'extension Naturalist
return_url: /www.notion.so/1a7a9a61c3f1800c8e32e893d6e7f430?pvs=21

community:
  title:
    en: Have additional questions? Want to be a part of our community?
    fr: Des questions supplémentaires ? Vous voulez faire partie de notre communauté ?
  join:
    en: Join our Discord!
    fr: Rejoignez notre Discord !
  discord_url: /discord.com/invite/starfishstudios

social_links:
  marketplace: /www.minecraft.net/en-us/marketplace/creator?name=Starfish%20Studios
  curseforge: /www.curseforge.com/members/starfish_studios/projects
  tiktok: /www.tiktok.com/@starfishstudios
  instagram: /www.instagram.com/starfishstudiosinc/
  twitter: /twitter.com/starfishstudios
  youtube: /www.youtube.com/@starfishstudios
  website: /starfish-studios.com/ 

potential_animals:
  - alligator
  - anglerfish
  - ant
  - anteater
  - badger
  - bass
  - beaver
  - bird
  - blobfish
  - boar
  - budgie
  - black_bear
  - beetle
  - capybara
  - catfish
  - cavefish
  - caterpillar
  - clam
  - crab
  - crow_&_raven
  - coyote
  - deer
  - desert_scorpion
  - dragonfly
  - duck
  - eagle
  - eel
  - elephant
  - fennec_fox
  - firefly
  - flamingo
  - flying_fish
  - fennec_fox
  - giant_isopod
  - giant_salamander
  - giraffe
  - goose
  - gorilla
  - grizzly_bear
  - hamster
  - hedgehog
  - hippo
  - hyena
  - iguana
  - jellyfish_&_small_jellyfish
  - jungle_scorpion
  - kakapo
  - kangaroo
  - kiwi
  - komodo_dragon
  - lion
  - lizard
  - mammoth
  - mole
  - monkey
  - moose
  - octopus
  - orca
  - otter
  - ostrich
  - owl
  - peafowl
  - penguin
  - piranha
  - platypus
  - racoon
  - rat
  - red_panda
  - rhino
  - seals
  - secretary_bird
  - shark
  - skunk
  - sloth
  - slug
  - snail
  - snake
  - squirrel
  - starfish
  - stingray
  - termite
  - tiger
  - tortoise
  - toucan
  - tree_frog
  - turkey
  - vulture
  - walrus
  - whale
  - zebra 